[workspace]
members = [
    "libraries/honeyos-pic",
    "libraries/honeyos-pci",
    "libraries/honeyos-dma",
    "libraries/honeyos-usb",
    "libraries/honeyos-hid",
    "binaries/pic",
    "binaries/pci",
    "binaries/pit",
    "binaries/pty",
    "binaries/serial",
    "binaries/xhci",
    "binaries/devd",
    "binaries/hid",
]
resolver = "2"

[profile.release]
panic = "abort"
opt-level = 3
debug = "full"
